//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klocman.UpdateSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Klocman.UpdateSystem.Properties.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateHelper.exe is missing, make sure your anti-virus is not interfering with the update process..
        /// </summary>
        internal static string Error_UpdateHelperMissing {
            get {
                return ResourceManager.GetString("Error_UpdateHelperMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        internal static string UpdateSystem_DownloadingTitle {
            get {
                return ResourceManager.GetString("UpdateSystem_DownloadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting....
        /// </summary>
        internal static string UpdateSystem_ExtractingTitle {
            get {
                return ResourceManager.GetString("UpdateSystem_ExtractingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all opened applications and try again. Make sure that your anti-virus program does not interfere with the update process.
        ///
        ///If the error persists visit the official website, and download a fresh copy of the application from there..
        /// </summary>
        internal static string UpdateSystem_Failed_Details {
            get {
                return ResourceManager.GetString("UpdateSystem_Failed_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files failed to extract or were removed.
        /// </summary>
        internal static string UpdateSystem_FailedExtractDetails {
            get {
                return ResourceManager.GetString("UpdateSystem_FailedExtractDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded update file is corrupted.
        /// </summary>
        internal static string UpdateSystem_FailedHash {
            get {
                return ResourceManager.GetString("UpdateSystem_FailedHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        internal static string UpdateSystem_FailedTitle {
            get {
                return ResourceManager.GetString("UpdateSystem_FailedTitle", resourceCulture);
            }
        }
    }
}
