//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateHelper.Properties.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update helper.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files are missing from the update data..
        /// </summary>
        internal static string RunAutoUpdate_Error_FilesMissing {
            get {
                return ResourceManager.GetString("RunAutoUpdate_Error_FilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic update failed, do you want to open the download page?
        ///
        ///Make sure your antivirus is not interrupting with the process. You might need to re-download the application manually because it could have been corrupted.
        ///
        /// Error details: {0}.
        /// </summary>
        internal static string RunAutoUpdate_ErrorBody {
            get {
                return ResourceManager.GetString("RunAutoUpdate_ErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data is missing..
        /// </summary>
        internal static string RunAutoUpdate_ErrorDataMissing {
            get {
                return ResourceManager.GetString("RunAutoUpdate_ErrorDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To look for updates you have to start the main application and then launch the update process from there..
        /// </summary>
        internal static string UserLaunchMessage {
            get {
                return ResourceManager.GetString("UserLaunchMessage", resourceCulture);
            }
        }
    }
}
